version: "3.0"

services:
  proxy:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./owasp-crs/rules:/etc/modsecurity/rules
    depends_on:
      - crs-updater
    environment:
      - PROXY_HOST=php
  php:
    image: nginx:latest
  crs-updater:
    image: pockost/modsecurity-crs
    volumes:
      - ./owasp-crs:/workdir
    environment:
      - CRS_BRANCH=origin/v3.0/master
    healthcheck:
      test: ["CMD", "test", "-d", "/workdir/.git"]
